server:
  port: 8081

spring:
  #服务名称
  application:
    name: application-data-center
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/application_data_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatisPlus配置
mybatis-plus:
  global-config:
    db-config:
      #全局主键策略
      id-type: assign_uuid
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
